# Generated by Django 5.2.6 on 2025-11-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_nalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='status_nalog',
            new_name='status_tax',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='nalog',
            new_name='tax',
        ),
    ]
