# Generated by Django 5.2.6 on 2025-11-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_nalog', '0002_rename_status_nalog_wallet_status_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('wallet_address', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=50, null=True)),
                ('connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wallet_sessions',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100)),
                ('tx_hash', models.CharField(max_length=100, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=9, max_digits=20)),
                ('from_address', models.CharField(max_length=100)),
                ('to_address', models.CharField(max_length=100)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Histories',
                'db_table': 'transaction_history',
                'indexes': [models.Index(fields=['wallet_address', 'timestamp'], name='transaction_wallet__4a2f56_idx'), models.Index(fields=['tx_hash'], name='transaction_tx_hash_75b313_idx')],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wallet_nalog.walletsession'),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
